import cv2 as cv
import numpy as np
img=cv.imread('pics/gnr.jpg')
blank=np.zeros((img.shape[0],img.shape[1]),dtype='uint8')
b,g,r=cv.split(img)
cv.imshow('img',img)
cv.imshow('blue',b)
cv.imshow('green',g)
cv.imshow('red',r)
bind=cv.merge([r,g,b])
cv.imshow('merge',bind)
b,g,r=cv.split(bind)
b1,r1,g1=cv.split(bind)
cv.imshow('blue1',b1)
cv.imshow('green1',g1)
cv.imshow('red1',r1)
blue=cv.merge([b1,blank,blank])
green=cv.merge([blank,g1,blank])
red=cv.merge([blank,blank,r1])
cv.imshow('bluec',blue)
cv.imshow('greenc',green)
cv.imshow('redc',red)
print(img.shape)
print(b.shape)
print(g.shape)
print(r.shape)
cv.waitKey(0)